# Copyright 2026 The Camoucrome Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

static_library("camoucfg") {
  sources = [
    "blink_scope.h",
    "coherence_validator.cc",
    "coherence_validator.h",
    "derive.cc",
    "derive.h",
    "invariants.h",
    "keys.h",
    "mask_config.cc",
    "mask_config.h",
    "mask_config_internal.cc",
    "mask_config_internal.h",
    "mouse_trajectories.cc",
    "mouse_trajectories.h",
  ]

  deps = [
    "//base",
    "//ui/gfx/geometry",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "coherence_validator_unittest.cc",
    "derive_unittest.cc",
    "keys_unittest.cc",
    "mask_config_unittest.cc",
    "mouse_trajectories_unittest.cc",
  ]

  deps = [
    ":camoucfg",
    "//base",
    "//base/test:test_support",
    "//testing/gtest",
    "//ui/gfx/geometry",
  ]
}
