// Copyright 2026 The Camoucrome Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef COMPONENTS_CAMOUCFG_INVARIANTS_H_
#define COMPONENTS_CAMOUCFG_INVARIANTS_H_

#include <array>
#include <string_view>

#include "components/camoucfg/keys.h"

// The invariant registry, in the form C++ compiles against.
//
// settings/invariants.json is the source of truth: it is what the fingerprint
// generator self-checks against and what the mutation tests are built from.
// This header is its generated form.
//
// It is generated BY HAND for now, exactly as keys.h is. A browser should not
// read a data file from disk at startup -- that adds a path to resolve, a
// failure mode when the file is missing or stale, and I/O on the startup path
// -- so the registry reaches C++ compiled in. SP6a owns replacing this with
// real generation and must keep these names identical so no call site moves.
//
// Until then CoherenceValidatorTest.RegistryMatchesGeneratedHeader asserts the
// two agree. A registry that has drifted from the code enforcing it is worse
// than no registry, because it reads as coverage while providing none.

namespace camoucfg::invariants {

enum class Policy {
  // Refuse to launch. For violations no repair can make plausible.
  kReject,
  // Fix deterministically and log the key, the old value and the new one.
  // Must be idempotent: validating the repaired output changes nothing.
  kRepair,
};

// What relation the listed keys must hold.
enum class Relation {
  // Every listed key that is present and recognised must describe the same
  // OS family, as camoucfg::OsFamily computes it. keys[0] is authoritative
  // when they disagree.
  kSameOsFamily,
};

struct Invariant {
  std::string_view id;
  Relation relation;
  Policy policy;
  // Fixed at two while every relation here is binary. A relation over more
  // keys will need this widened, and widening it is the moment to check that
  // every relation still knows how many keys it reads.
  std::array<std::string_view, 2> keys;
};

// Adding an entry here without adding it to settings/invariants.json, or
// without a mutation exercising it, is what the guard tests exist to catch:
// RegistryMatchesGeneratedHeader for the first, MutationsExistForEveryInvariant
// for the second.
inline constexpr std::array<Invariant, 1> kAllInvariants = {{
    {"ua-os-family-agrees",
     Relation::kSameOsFamily,
     Policy::kRepair,
     {"ua:osInfo", "ua:platform"}},
}};

// Not wrapped in an anonymous namespace: Google's style guide forbids one in
// a header (cpplint's build/namespaces_headers) because it gives every
// including translation unit its own private copy of these entities instead
// of sharing one. A `constexpr` free function is implicitly `inline`
// ([dcl.constexpr]), which already gives it the external-with-shared-
// -definition linkage a header needs -- the anonymous namespace bought
// nothing here except the lint violation.
//
// coherence_validator.cc's ValidateAtStartup() does not read `policy` at
// all -- it branches only on CAMOU_CONFIG_STRICT, which is correct only
// because every entry today is Policy::kRepair. A Policy::kReject entry
// would compile, pass every existing test, and be reported and treated
// exactly like a kRepair one: read and NOT refused outside strict mode. This
// assertion is what makes that assumption falsifiable at build time instead
// of silently wrong -- the first kReject entry must fail here, forcing
// ValidateAtStartup() to actually branch on it, rather than fail nowhere.
constexpr bool AllPoliciesAreRepair() {
  for (const Invariant& inv : kAllInvariants) {
    if (inv.policy != Policy::kRepair) {
      return false;
    }
  }
  return true;
}

// coherence_validator.cc's CheckSameOsFamily() dispatches which string
// format applies with `key == keys::kUaOsInfo` and treats every other key as
// a UA-CH platform token, then always repairs keys[1] to
// CanonicalUaChPlatformFor(OsFamilyOfKey(keys[0])). A kSameOsFamily entry
// whose keys[0] is not kUaOsInfo would still compile and still run: it would
// read keys[0] with the wrong parser and repair keys[1] to a value derived
// from a misread, with nothing anywhere naming the mistake.
//
// The same is true of keys[1]: CheckSameOsFamily() always repairs it as a
// UA-CH platform token via CanonicalUaChPlatformFor(), so an entry whose
// keys[1] is not kUaPlatform -- e.g. {kUaOsInfo, "navigator.platform"} --
// would compile and run too, reading that key with
// OsFamilyFromUaChPlatform() (which does not understand navigator.platform's
// values, e.g. "Win32", so the entry would simply never fire) and, if it
// somehow did, repairing it to a UA-CH token rather than whatever format that
// key actually expects. Checked here alongside keys[0] for the same reason:
// nothing else in the codebase would ever notice.
constexpr bool EverySameOsFamilyEntryUsesTheUaKeyPair() {
  for (const Invariant& inv : kAllInvariants) {
    if (inv.relation == Relation::kSameOsFamily &&
        (inv.keys[0] != keys::kUaOsInfo || inv.keys[1] != keys::kUaPlatform)) {
      return false;
    }
  }
  return true;
}

static_assert(
    AllPoliciesAreRepair(),
    "a Policy::kReject entry would be silently read and reported as though "
    "it were kRepair -- coherence_validator.cc's ValidateAtStartup() does "
    "not branch on policy. Implement kReject handling there first.");

static_assert(
    EverySameOsFamilyEntryUsesTheUaKeyPair(),
    "a kSameOsFamily entry must list kUaOsInfo as keys[0] and kUaPlatform as "
    "keys[1] -- coherence_validator.cc's CheckSameOsFamily() dispatches on "
    "`key == keys::kUaOsInfo` and always repairs keys[1] via "
    "CanonicalUaChPlatformFor(), so any other keys[0] or keys[1] would be "
    "read or repaired wrongly with no diagnostic.");

}  // namespace camoucfg::invariants

#endif  // COMPONENTS_CAMOUCFG_INVARIANTS_H_
