// Copyright 2026 The Camoucrome Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef COMPONENTS_CAMOUCFG_INVARIANTS_H_
#define COMPONENTS_CAMOUCFG_INVARIANTS_H_

#include <array>
#include <string_view>

// The invariant registry, in the form C++ compiles against.
//
// settings/invariants.json is the source of truth: it is what the fingerprint
// generator self-checks against and what the mutation tests are built from.
// This header is its generated form.
//
// It is generated BY HAND for now, exactly as keys.h is. A browser should not
// read a data file from disk at startup -- that adds a path to resolve, a
// failure mode when the file is missing or stale, and I/O on the startup path
// -- so the registry reaches C++ compiled in. SP6a owns replacing this with
// real generation and must keep these names identical so no call site moves.
//
// Until then CoherenceValidatorTest.RegistryMatchesGeneratedHeader asserts the
// two agree. A registry that has drifted from the code enforcing it is worse
// than no registry, because it reads as coverage while providing none.

namespace camoucfg::invariants {

enum class Policy {
  // Refuse to launch. For violations no repair can make plausible.
  kReject,
  // Fix deterministically and log the key, the old value and the new one.
  // Must be idempotent: validating the repaired output changes nothing.
  kRepair,
};

// What relation the listed keys must hold.
enum class Relation {
  // Every listed key that is present and recognised must describe the same
  // OS family, as camoucfg::OsFamily computes it. keys[0] is authoritative
  // when they disagree.
  kSameOsFamily,
};

struct Invariant {
  std::string_view id;
  Relation relation;
  Policy policy;
  // Fixed at two while every relation here is binary. A relation over more
  // keys will need this widened, and widening it is the moment to check that
  // every relation still knows how many keys it reads.
  std::array<std::string_view, 2> keys;
};

// Adding an entry here without adding it to settings/invariants.json, or
// without a mutation exercising it, is what the guard tests exist to catch:
// RegistryMatchesGeneratedHeader for the first, MutationsExistForEveryInvariant
// for the second.
inline constexpr std::array<Invariant, 1> kAllInvariants = {{
    {"ua-os-family-agrees",
     Relation::kSameOsFamily,
     Policy::kRepair,
     {"ua:osInfo", "ua:platform"}},
}};

}  // namespace camoucfg::invariants

#endif  // COMPONENTS_CAMOUCFG_INVARIANTS_H_
