#!/usr/bin/env python3
"""Generates additions/camoucfg/keys.h from settings/keys.json.

settings/keys.json is the registry's single source of truth (SP6 §4.6): the
C++ constants here and the client's validation table (A4) are both derived
from it, so a key cannot exist for one consumer and not the other.

    scripts/gen_keys.py          rewrite keys.h
    scripts/gen_keys.py --check  exit 1 if keys.h is stale, if the unit test's
                                 `declared` set disagrees with the registry, or
                                 if any camoucfg::Get*/HasKey call site passes a
                                 string literal where a keys:: constant belongs

The generated header is committed (not a GN action): the Chromium tree gets
it through additions/ like every other file, and --check is the drift gate.
"""
import glob
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTRY = os.path.join(ROOT, "settings", "keys.json")
HEADER = os.path.join(ROOT, "additions", "camoucfg", "keys.h")
UNITTEST = os.path.join(ROOT, "additions", "camoucfg", "keys_unittest.cc")
TYPES = {"string", "uint32", "int32", "double", "bool", "string_list", "list",
         "dict", "unsupported"}
UA_METADATA = ["kUaPlatform", "kUaPlatformVersion", "kUaArchitecture",
               "kUaBitness", "kUaModel", "kUaMobile", "kUaWow64"]

PREAMBLE = """\
// Copyright 2026 The Camoucrome Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef COMPONENTS_CAMOUCFG_KEYS_H_
#define COMPONENTS_CAMOUCFG_KEYS_H_

#include <array>
#include <string_view>

// The registry of configuration keys.
//
// GENERATED by scripts/gen_keys.py from settings/keys.json -- edit the JSON,
// rerun the script, commit both. `scripts/gen_keys.py --check` fails while
// this file is stale.
//
// Its purpose is that keys stop being string literals at call sites. A key
// mistyped at one of two sites that should agree produces a surface that
// silently follows a knob nobody set, and neither the compiler nor a reviewer
// reading one file can see it. The same JSON feeds the client's validation
// table, so a key the browser reads is always one the client can generate.
//
// Naming rule, from 00-conventions.md: a dot when the key mirrors a JavaScript
// property path exactly, a colon when it names a synthetic namespace with no
// direct JS counterpart. A value derived from another gets no key at all.

namespace camoucfg::keys {

"""

ALL_KEYS_COMMENT = """\
// Every key above, in registry order.
"""

EPILOGUE = """\

// The UA client-hint keys, without kUaOsInfo.
//
// The split is what the list is for. These eight reach
// navigator.userAgentData and the Sec-CH-UA-* headers; kUaOsInfo reaches the
// user-agent string. Setting any of these without kUaOsInfo produces a
// fingerprint that contradicts itself on two surfaces a page reads for free,
// so startup warns about exactly that combination and needs the group by name
// rather than as eight open-coded HasKey calls that a later key would silently
// fall out of.
inline constexpr std::array<std::string_view, 8> kUaMetadataKeys = {
    kUaPlatform, kUaPlatformVersion, kUaArchitecture, kUaBitness,
    kUaModel,    kUaMobile,          kUaWow64,        kUaBrand,
};

}  // namespace camoucfg::keys

#endif  // COMPONENTS_CAMOUCFG_KEYS_H_
"""


def load():
    with open(REGISTRY) as f:
        keys = json.load(f)["keys"]
    names, values = set(), set()
    for e in keys:
        assert re.fullmatch(r"k[A-Z]\w*", e["name"]), e["name"]
        assert e["type"] in TYPES, (e["name"], e["type"])
        assert re.search(r"[.:]", e["key"]) and " " not in e["key"], e["key"]
        assert e["name"] not in names, "duplicate name " + e["name"]
        assert e["key"] not in values, "duplicate key " + e["key"]
        names.add(e["name"])
        values.add(e["key"])
    for n in UA_METADATA:
        assert n in names, n
    return keys


def render(keys):
    out = [PREAMBLE]
    for i, e in enumerate(keys):
        if "doc" in e and i and e.get("gap", True):
            out.append("\n")
        for line in e.get("doc", []):
            out.append(("// " + line).rstrip() + "\n")
        decl = f'inline constexpr char {e["name"]}[] = "{e["key"]}";'
        if len(decl) > 80:
            decl = f'inline constexpr char {e["name"]}[] =\n    "{e["key"]}";'
        out.append(decl + "\n")
    out.append("\n" + ALL_KEYS_COMMENT)
    out.append(f"inline constexpr std::array<std::string_view, {len(keys)}> kAllKeys = {{\n")
    out.extend(f"    {e['name']},\n" for e in keys)
    out.append("};\n")
    out.append(EPILOGUE)
    return "".join(out)


def check(keys, rendered):
    problems = []
    with open(HEADER) as f:
        if f.read() != rendered:
            problems.append("additions/camoucfg/keys.h is stale: run scripts/gen_keys.py")
    with open(UNITTEST) as f:
        m = re.search(r"declared = \{(.*?)\};", f.read(), re.S)
    declared = set(re.findall(r"k\w+", m.group(1)))
    names = {e["name"] for e in keys}
    for n in sorted(names - declared):
        problems.append(f"keys_unittest.cc `declared` lacks {n}")
    for n in sorted(declared - names):
        problems.append(f"keys_unittest.cc `declared` has {n}, not in settings/keys.json")
    for name, no in patch_literal_hits(os.path.join(ROOT, "patches")):
        with open(os.path.join(ROOT, "patches", name)) as f:
            line = f.readlines()[no - 1]
        problems.append(f"patches/{name}:{no}: string literal in key position: {line.strip()}")
    for path in sorted(glob.glob(os.path.join(ROOT, "additions", "camoucfg", "*.cc")) +
                       glob.glob(os.path.join(ROOT, "additions", "camoucfg", "*.h"))):
        if path.endswith("_unittest.cc"):
            continue
        with open(path) as f:
            lines = f.readlines()
        for no in literal_key_lines(lines, False):
            problems.append(f"{os.path.relpath(path, ROOT)}:{no}: string literal in key position: {lines[no - 1].strip()}")
    return problems


def patch_literal_hits(patches_dir):
    """(patch, line) literal-key hits that survive the series: a call a later
    patch in `series` removes again never reaches the applied tree."""
    with open(os.path.join(patches_dir, "series")) as f:
        names = [l.strip() for l in f if l.strip() and not l.startswith("#")]
    hits, removed_later = [], set()
    for name in reversed(names):
        with open(os.path.join(patches_dir, name)) as f:
            lines = f.readlines()
        cur, files = None, []  # the file each patch line belongs to (its +++ b/ header)
        for l in lines:
            cur = l[6:].strip() if l.startswith("+++ b/") else cur
            files.append(cur)
        # ponytail: matched by (file, text), not position; an identical line removed
        # elsewhere in the same file would hide a hit. Apply the series if that bites.
        for start, end in literal_key_spans(lines, True):
            if not all((files[i - 1], lines[i - 1][1:]) in removed_later for i in range(start, end + 1)):
                hits.append((name, start))
        removed_later |= {(fn, l[1:]) for fn, l in zip(files, lines) if l.startswith("-") and not l.startswith("---")}
    return sorted(hits)


# Presubmit (SP6 §4.6): no string literal in the key position of a getter.
# The first argument may hold one level of parentheses (ScopeFor(ctx)) and the
# call may span lines, so this runs over the whole text, not line by line.
LITERAL_KEY = re.compile(r'\b(?:camoucfg::)?(?:Get(?:String|Uint32|Int32|Double|Bool|StringList)|HasKey)'
                         r'\(\s*(?:[^,()]|\([^()]*\))*,\s*"')


def literal_key_spans(lines, patch):
    """1-based (first, last) lines of each getter call whose key argument is a string literal."""
    if patch:  # drop removed lines and the +/space marker column, keep numbering
        lines = ["\n" if l.startswith("-") else l[1:] for l in lines]
    text = "".join(lines)
    return [(text.count("\n", 0, m.start()) + 1, text.count("\n", 0, m.end()) + 1)
            for m in LITERAL_KEY.finditer(text)]


def literal_key_lines(lines, patch):
    """1-based line numbers where a getter's key argument is a string literal."""
    return [start for start, _ in literal_key_spans(lines, patch)]


def main(argv):
    keys = load()
    rendered = render(keys)
    if "--check" in argv:
        problems = check(keys, rendered)
        for p in problems:
            print("FAIL ", p)
        if problems:
            return 1
        print(f"PASS  keys.h matches settings/keys.json ({len(keys)} keys); unit-test set and call sites consistent")
        return 0
    with open(HEADER, "w") as f:
        f.write(rendered)
    print(f"wrote {os.path.relpath(HEADER, ROOT)} ({len(keys)} keys)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
