#!/usr/bin/env python3
"""settings/fonts.json -> settings/fontconfig/{windows,macos}.conf. --check refuses drift.

Strong bindings are load-bearing: Skia's fontconfig manager
(SkFontMgr_fontconfig::matchFamilyStyle) accepts a match only when the
resolved family equals the request under strong binding; fontconfig's
default weak fallback is what Chrome reports as "font not found". The conf
lists the bundled directory only (<root>/fonts, relative to the conf at
<root>/settings/fontconfig/, so the archive extracts anywhere) and an xdg cache dir so launches do not rescan.
"""
import json
import pathlib
import sys
from xml.sax.saxutils import escape

ROOT = pathlib.Path(__file__).resolve().parent.parent
FILES = {"Windows": "windows.conf", "macOS": "macos.conf"}


def alias_target(fonts, os_name, family):
    if family in fonts["alias"]:
        return fonts["alias"][family]
    if any(family in b["provides"] for b in fonts["bundle"]):
        return family  # a bundled file carrying the claimed name (Wine's Tahoma) resolves as itself
    for cls, names in fonts["script_class"].items():
        if family in names:
            return fonts["class_font"][os_name][cls]
    return fonts["class_font"][os_name]["sans"]


def fontconfig_xml(fonts, os_name):
    bundled = {f for b in fonts["bundle"] for f in b["provides"]}
    families = sorted((set(fonts["families"][os_name]["list"]) | set(fonts["alias"])) - bundled)
    out = ['<?xml version="1.0"?>', '<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">',
           f'<!-- generated by scripts/gen_fontconfig.py from settings/fonts.json for a {os_name} claim; do not edit -->',
           '<fontconfig>', '  <dir prefix="relative">../../fonts</dir>',
           '  <cachedir prefix="xdg">camoucrome-fontconfig</cachedir>']
    for generic, target in fonts["generic"][os_name].items():
        out.append(f'  <alias binding="strong"><family>{escape(generic)}</family><prefer><family>{escape(target)}</family></prefer></alias>')
    for fam in families:
        out.append(f'  <alias binding="strong"><family>{escape(fam)}</family><prefer><family>{escape(alias_target(fonts, os_name, fam))}</family></prefer></alias>')
    out += ['</fontconfig>', '']
    return "\n".join(out)


def alias_map(fonts, os_name):
    """Every captured or explicitly aliased family -> its bundled target, minus
    identities: what the generator emits as fonts:alias (the C++ FontCache
    alias; fontconfig's own alias cannot rename a match for Skia)."""
    bundled = {f for b in fonts["bundle"] for f in b["provides"]}
    out = {}
    for fam in sorted(set(fonts["families"][os_name]["list"]) | set(fonts["alias"]) | set(fonts["generic"][os_name])):
        target = fonts["generic"][os_name].get(fam) or alias_target(fonts, os_name, fam)
        if fam not in bundled and target != fam:
            out[fam] = target
    return out


def main():
    fp = ROOT / "settings" / "fonts.json"
    fonts = json.loads(fp.read_text(encoding="utf-8"))
    check = "--check" in sys.argv
    bad = 0
    want_map = {os_name: alias_map(fonts, os_name) for os_name in FILES}
    if fonts.get("alias_map") != want_map:
        if check:
            print("STALE settings/fonts.json alias_map")
            bad += 1
        else:
            fonts["alias_map"] = want_map
            fp.write_text(json.dumps(fonts, indent=1, ensure_ascii=False) + "\n")
            print("wrote alias_map into settings/fonts.json:", {k: len(v) for k, v in want_map.items()})
    for os_name, f in FILES.items():
        p = ROOT / "settings" / "fontconfig" / f
        want = fontconfig_xml(fonts, os_name)
        if check:
            if not p.exists() or p.read_text() != want:
                print(f"STALE {p}")
                bad += 1
        else:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(want)
            print(f"wrote {p} ({want.count('<alias')} aliases)")
    if check:
        print("PASS fontconfig files match settings/fonts.json" if not bad else f"FAIL {bad} stale")
        sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
